frontend/package-lock.json, frontend/package.json, frontend/src/components/Pages/contact/Contact.tsx
Finished contact form w/ TS. Email functionalities working. Ready to be reviewed/merged.
=> Team33 51 creating contact page

.env, backend/.env, backend/.gitignore, backend/package-lock.json, backend/package.json, backend/src/controllers/loginController.ts, backend/src/controllers/logoutController.ts, backend/src/controllers/signupController.ts, backend/src/index.ts, backend/src/models/farmer.ts, backend/src/mongoconfig.ts
1. Add the controller and route for login and logout.
2. Add the necessary package for JWT and cookie.
3. Please run the npm install to install the new package.
=> Team33 49 login backend

frontend/src/components/Nav/Navbar.css
=> made the navbar links container wider - Becky

frontend/jest.config.cjs, frontend/package-lock.json, frontend/package.json, frontend/src/components/Pages/signUp/SignUp.test.tsx, frontend/src/components/Pages/signUp/SignUp.tsx, frontend/src/components/Pages/signUp/signUp.css, frontend/src/global.d.ts, frontend/src/main.tsx
Added SignUp, finished SignUp test
=> #38 farmer signup frontend

backend/multerSetup.js, backend/package-lock.json, backend/package.json
The Listing image will be saved in a folder created on the frontend side of the app
=> 59 listing image storage

backend/package-lock.json, backend/package.json, backend/src/index.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/Pages/login/Login.tsx, frontend/src/components/Pages/login/login.css, frontend/src/components/Pages/signUp/SignUp.tsx, frontend/src/components/Pages/signUp/signUp.css, frontend/src/main.tsx
Updated signup and login components to send requests to backend end points.
Minor changes to main.tsx to import from react-dom/client for createRoot - Chrome dev tools gave me errors about this.
Also emailjs is causing issues on every branch I create so I think the development branch needs to be checked for the correct frontend dependancies. Suggestion - need to use **npm i @emailjs/browser --save** to the development branch (frontend).
=> 60 frontend login request

backend/src/controllers/jwtVerification.ts, backend/src/controllers/productCreateController.ts, backend/src/controllers/productListController.ts, backend/src/index.ts, backend/src/models/farmer.ts, backend/src/models/product.ts
1. Add product Schema
2. Add controller create a product
3. Add controller list all products
4. without considering img, need to be merged with img function.
=> Backend product listing add

frontend/package-lock.json, frontend/package.json, frontend/src/components/Pages/productUploadForm/ProductUploadForm.tsx, frontend/src/components/Pages/productUploadForm/productUploadForm.css
I've added CSS to make the form look more like a form. There were issues with the layout and labels for each input. It has all been sorted now and ready to be merged.
=> Team33 57 farmer create/upload page add css

frontend/src/components/Search/Search.tsx, frontend/src/components/Search/search.css, frontend/src/components/Search/searchResultCard.tsx
Using a fake api for now to get functionality working - needs some improvements to the CSS.
=> 64 search term to backend

backend/.env, backend/package-lock.json, backend/src/controllers/getUserContextController.ts, backend/src/controllers/jwtVerification.ts, backend/src/controllers/loginController.ts, backend/src/index.ts, backend/src/utils/interface.ts, frontend/src/App.tsx, frontend/src/components/Nav/Navbar.tsx, frontend/src/components/Pages/login/Login.tsx, frontend/src/utils/UserContext.tsx, frontend/src/utils/interface.tsx
1. frontend: add useContext for currentUser and interface 
2. backend: add payrol in the token for user verification and decoded 
3.for both FE and BE, intergrate the new user interface and solve cors issue. 
4. improve the navbar.
=> integrated the token and useContext for both frontend and backend

frontend/src/components/Pages/help/Help.tsx, frontend/src/components/Pages/help/help.css
Created text and a bit for styling for help page in same style as about page.
=> added in text for Help page

frontend/src/components/Pages/about/About.tsx, frontend/src/components/Pages/about/about.css
created text for about page and done some basic styling.
=> About page created

frontend/src/components/Pages/homePage/HomePage.tsx, frontend/src/components/Pages/login/Login.tsx, frontend/src/components/Search/Search.tsx
Made some minor fixes to the product search before starting on postcode search.
=> 75b postcode search feature

frontend/src/components/Pages/about/About.tsx, frontend/src/components/Pages/about/about.css
Reformatted and styled about page in same style as help page, looks cleaner and brighter now.
=> added picture and reformatted about page

frontend/index.html, frontend/src/App.css, frontend/src/App.tsx, frontend/src/components/Nav/Navbar.tsx, frontend/src/components/Pages/about/about.css, frontend/src/components/Pages/help/Help.tsx, frontend/src/components/Pages/help/help.css, frontend/src/components/Pages/homePage/homePage.css, frontend/src/components/Pages/login/Login.tsx, frontend/src/components/Pages/login/login.css, frontend/src/components/Pages/preSignup/PreSignup.tsx, frontend/src/components/Pages/preSignup/preSignup.css, frontend/src/components/Pages/productUploadForm/productUploadForm.css, frontend/src/components/Pages/signUp/SignUp.tsx, frontend/src/components/Pages/signUp/signUp.css, frontend/src/components/Search/search.css, frontend/src/index.css, frontend/src/main.tsx
deleted duplicated css, created global css, unified signup css, login
=> Globalcss signup

frontend/src/components/Pages/productUploadForm/ProductUploadForm.tsx, frontend/src/components/Pages/productUploadForm/productUploadForm.css, frontend/src/components/Pages/signUp/signUp.css
css-uploadform, and price /qunaity should not be negative
=> css-uploadform, and price /qunaity should not be negative.

frontend/src/components/Pages/homePage/HomePage.tsx, frontend/src/components/Pages/login/Login.tsx, frontend/src/components/Pages/login/login.css, frontend/src/components/Pages/signUp/SignUp.tsx, frontend/src/components/Pages/signUp/signUp.css, frontend/src/components/Search/Search.tsx, frontend/src/components/Search/search.css, frontend/src/components/Search/searchResultCard.tsx, frontend/src/components/Search/searchResults.css
Search bar and option buttons are now in one row - the option buttons logic need tweaking still.
=> 91 simplify search w globalcss

frontend/src/components/Nav/Navbar.css, frontend/src/components/Pages/about/about.css, frontend/src/components/Pages/help/help.css, frontend/src/components/Pages/homePage/HomePage.tsx, frontend/src/components/Search/Search.tsx, frontend/src/components/Search/search.css, frontend/src/components/Search/searchResults.css
Made some adjustments for Shanis regarding the search results cards.
Minor other tweaks - added margin to Home link, added margin top to Help and About images so they weren't at the top of the screen anymore.
=> adjusted some css in search results

README.md
have added in suggestions from Becky, all should be good now with readme!
=> final? changes done to readme

backend/src/controllers/productCreateController.ts
fix an important bug in the backend for uploading a product. I am not sure when and why this bug appear but finally I fix it.
=> 96-fix-bug-upload-product

backend/src/controllers/productDeleteController.ts, backend/src/index.ts, frontend/src/components/Pages/productDetails/ProductDetailCard.tsx, frontend/src/components/Pages/productDetails/ProductDetails.tsx, frontend/src/components/Pages/productDetails/deleteProduct.tsx, frontend/src/components/Pages/productDetails/productDetailsCard.css
Hoping this works - I am attempting a PR from my forked repo to the development branch of the farmers display and delete button.
=> 42 farmers produce displayed

frontend/src/components/Pages/about/About.tsx, frontend/src/components/Pages/about/about.css, frontend/src/components/Pages/help/Help.tsx, frontend/src/components/Pages/help/help.css
Changed the html and css a little for About Us and Help pages.
=> fixed text paragraphs in about us and help pages
